apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ca-imfreemobile-com
  name: ca-imfreemobile-com
spec:
  ports:
  - name: "7054"
    port: 7054
    targetPort: 7054
  selector:
    io.kompose.service: ca-imfreemobile-com
status:
  loadBalancer: {}
