apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: couchdb
  name: couchdb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: couchdb
    spec:
      containers:
      - env:
        - name: COUCHDB_PASSWORD
        - name: COUCHDB_USER
        image: hyperledger/fabric-couchdb:0.4.10
        name: couchdb
        ports:
        - containerPort: 5984
        resources: {}
      restartPolicy: Always
status: {}
