apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cli
  template:
    metadata:
      labels:
        component: cli
    spec:
      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: cli
          image: rowelgutierrez/fabric-workspace:latest
          imagePullPolicy: Never
          tty: true
          workingDir: /var/hyperledger/fabric/peer
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /host/var/run/docker.sock
              name: dockersocket
            - name: shared-volume
              mountPath: /var/hyperledger/fabric/peer/channel-artifacts
              subPath: channel-artifacts
            - name: shared-volume
              mountPath: /var/hyperledger/fabric/peer/crypto-config
              subPath: crypto-config
            - name: shared-volume
              mountPath: /var/hyperledger/fabric/peer/lock
              subPath: lock
          env:
            - name: TZ
              value: "UTC"
            - name: DEV_MODE
              value: "false"
            - name: CORE_VM_ENDPOINT
              value: unix:///host/var/run/docker.sock
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "false"
            - name: CORE_PEER_NETWORKID
              value: "nid1"
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric
            - name: FABRIC_LOGGING_SPEC
              value: info
            - name: CORE_PEER_ID
              value: cli
            - name: CORE_PEER_ADDRESS
              value: peer0-org1-imfreemobile-com:7051
            - name: CA_ADDRESS
              value: ca-imfreemobile-com
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: CORE_PEER_MSPID
              value: Org1MSP
            - name: CORE_CHAINCODE_KEEPALIVE
              value: "10"
            - name: GODEBUG
              value: "netdns=go"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /var/hyperledger/fabric/peer/crypto-config/peerOrganizations/org1.imfreemobile.com/peers/peer0.org1.imfreemobile.com/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /var/hyperledger/fabric/peer/crypto-config/peerOrganizations/org1.imfreemobile.com/peers/peer0.org1.imfreemobile.com/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /var/hyperledger/fabric/peer/crypto-config/peerOrganizations/org1.imfreemobile.com/peers/peer0.org1.imfreemobile.com/tls/ca.crt
            - name: CORE_PEER_MSPCONFIGPATH
              value: /var/hyperledger/fabric/peer/crypto-config/peerOrganizations/org1.imfreemobile.com/users/Admin@org1.imfreemobile.com/msp