apiVersion: v1
data:
  0952e834bb9b1901ffaebb02fc71052627dfd3ceb6b8d57e62183cdd8059d0b5_sk: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2kweWNGaFRjRTZWTlFId3IKTFlJWEI4eU40NXJqMEw4OFpxNFB6V3F4MlZ1aFJBTkNBQVJLa05pZFEraGtVOVJCVVFlOXNBL2YrMlRiK29UVAp3UmpiNkJSTXhNREU3ZHFQVVB0MU9rTmc2QjdZWGlGbnRsbGt1N3Z2ZUMzejZkL2dqbGQzeHVHWAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  creationTimestamp: "2019-09-29T05:14:12Z"
  name: o-cert-admin-msp-keystore
  namespace: default
  resourceVersion: "13340"
  selfLink: /api/v1/namespaces/default/secrets/o-cert-admin-msp-keystore
  uid: 698a41a6-fb54-4936-a616-34a35471c355
type: Opaque
