apiVersion: v1
data:
  tlsca.imfreemobile.com-cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNWekNDQWY2Z0F3SUJBZ0lSQU8wWldhc0hnNCtNaGRxNGtwKzZXZTR3Q2dZSUtvWkl6ajBFQXdJd2RqRUwKTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnVENrTmhiR2xtYjNKdWFXRXhGakFVQmdOVkJBY1REVk5oYmlCRwpjbUZ1WTJselkyOHhHVEFYQmdOVkJBb1RFR2x0Wm5KbFpXMXZZbWxzWlM1amIyMHhIekFkQmdOVkJBTVRGblJzCmMyTmhMbWx0Wm5KbFpXMXZZbWxzWlM1amIyMHdIaGNOTVRrd09UTXdNVE15TkRBd1doY05Namt3T1RJM01UTXkKTkRBd1dqQjJNUXN3Q1FZRFZRUUdFd0pWVXpFVE1CRUdBMVVFQ0JNS1EyRnNhV1p2Y201cFlURVdNQlFHQTFVRQpCeE1OVTJGdUlFWnlZVzVqYVhOamJ6RVpNQmNHQTFVRUNoTVFhVzFtY21WbGJXOWlhV3hsTG1OdmJURWZNQjBHCkExVUVBeE1XZEd4elkyRXVhVzFtY21WbGJXOWlhV3hsTG1OdmJUQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDkKQXdFSEEwSUFCRUFUWDRSRHlEa1Vidm0weFRxNXdXWTd5enY2TEVTYkhCRGJ3VnVsWWxCZTA3MzZkR3BXaTRTdgpuS2k2aUJORmh4VGNNZUNTRk5nV0lBbjlieVFVaVllamJUQnJNQTRHQTFVZER3RUIvd1FFQXdJQnBqQWRCZ05WCkhTVUVGakFVQmdnckJnRUZCUWNEQWdZSUt3WUJCUVVIQXdFd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBcEJnTlYKSFE0RUlnUWdYVjNPdHROTWdvdHdLdGNXZ01ZbG5yVnZWUzg4M0lUWklqMVRUa1liazJFd0NnWUlLb1pJemowRQpBd0lEUndBd1JBSWdjWFVqUmxCajhHQ3NjOWtGMitvbFZwSHpteXJ1L09BRytwTnFsZWxrQ1p3Q0lGRU5vbmpvCngvRkkxWi9ETUZLVUJ1SUFFOUM1QlhsV1pUWHh2R080dmxweQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
kind: Secret
metadata:
  creationTimestamp: "2019-09-30T13:34:58Z"
  name: o-cert-admin-msp-tlscacerts
  namespace: default
  resourceVersion: "614"
  selfLink: /api/v1/namespaces/default/secrets/o-cert-admin-msp-tlscacerts
  uid: d2f24aaa-d878-4e1a-b007-c007d18b4051
type: Opaque
