apiVersion: v1
data:
  8e9d45fa6f5a20c1724fd0e09ac8452f3f3f02b82aed1ba4fb662a054f4b208d_sk: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ1dsZGQ1OW1BMEk0RjFMR0wKb2xqall1K2xxV3NnOEdCUEFXNHg1cmZpWHFhaFJBTkNBQVR6N01QQmdWODFOWkFmZVBqUjAwQ3hnb3dwVDdQVQpEanpGR05acHMvcnlyWFJ0Yzc1L1pqdHVHNkZxNmpwc1ZLSk02ZElWYk41RjR4R05qMUd5bUtuegotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  creationTimestamp: "2019-09-29T06:51:15Z"
  name: p-cert-peer-msp-keystore
  namespace: default
  resourceVersion: "21893"
  selfLink: /api/v1/namespaces/default/secrets/p-cert-peer-msp-keystore
  uid: e81400a7-7e31-45a9-9d94-d6cfe768b5e7
type: Opaque
