apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ca-imfreemobile-com
  template:
    metadata:
      labels:
        component: ca-imfreemobile-com
    spec:
      initContainers:
        - name: configmap-copy
          image: busybox
          command: ['/bin/sh', '-c', 'cp /etc/hyperledger/files/* /etc/hyperledger/']
          volumeMounts:
            - name: ca-storage-mount
              mountPath: /etc/hyperledger/files
            - name: ca-storage
              mountPath: /etc/hyperledger
      volumes:
        - name: ca-storage-mount
          secret:
            secretName: o-cert-ca
        - name: ca-storage
          emptyDir: {}
      containers:
        - name: ca-imfreemobile-com
          image: hyperledger/fabric-ca:1.4.1
          ports:
            - containerPort: 7054
          volumeMounts:
            - name: ca-storage
              mountPath: /etc/hyperledger/fabric-ca-server-config
              readOnly: false
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca-cluster-ip-service
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: /etc/hyperledger/fabric-ca-server-config/ca.imfreemobile.com-cert.pem
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: /etc/hyperledger/fabric-ca-server-config/af02abd1c33fa7107b765763ec9cbd457a12881dc62746f962be463a31890bd8_sk
          command: ["sh"]
          args: ["-c", "fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.imfreemobile.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/af02abd1c33fa7107b765763ec9cbd457a12881dc62746f962be463a31890bd8_sk -b admin:adminpw -d"]