apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ca-imfreemobile-com
  template:
    metadata:
      labels:
        component: ca-imfreemobile-com
    spec:
      volumes:
        - name: ca-storage
          secret:
            secretName: ca-ssl
      containers:
        - name: ca-imfreemobile-com
          image: hyperledger/fabric-ca:1.4.1
          ports:
            - containerPort: 7054
          volumeMounts:
            - name: ca-storage
              mountPath: /etc/hyperledger/fabric-ca-server-config
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca-cluster-ip-service
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: /etc/hyperledger/fabric-ca-server-config/ca.pem
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: /etc/hyperledger/fabric-ca-server-config/ca_key