apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: couchdb
  template:
    metadata:
      labels:
        component: couchdb
    spec:
      containers:
        - name: couchdb
          image: hyperledger/fabric-couchdb:0.4.10
          ports:
            - containerPort: 5984
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: COUCHDB_USER
              value: ""
            - name: COUCHDB_PASSWORD
              value: ""