apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orderer-imfreemobile-com
  template:
    metadata:
      labels:
        component: orderer-imfreemobile-com
    spec:
      initContainers:
        - name: configmap-copy
          image: busybox
          command: ['/bin/sh', '-c']
          args: ['cp -R /etc/hyperledger/msp/orderer/files/* /etc/hyperledger/msp/orderer/ && cp -R /etc/hyperledger/configtx/files/* /etc/hyperledger/configtx/ && cp -R /etc/hyperledger/msp/peerOrg1/files/* /etc/hyperledger/msp/peerOrg1/']
          volumeMounts:
            - name: orderer-storage
              mountPath: /etc/hyperledger/msp/orderer
            - name: peer-storage
              mountPath: /etc/hyperledger/msp/peerOrg1
            - name: configtx
              mountPath: /etc/hyperledger/configtx
            - name: orderer-msp-admincerts-mount
              mountPath: /etc/hyperledger/msp/orderer/files/msp/admincerts
            - name: orderer-msp-cacerts-mount
              mountPath: /etc/hyperledger/msp/orderer/files/msp/cacerts
            - name: orderer-msp-keystore-mount
              mountPath: /etc/hyperledger/msp/orderer/files/msp/keystore
            - name: orderer-msp-signcerts-mount
              mountPath: /etc/hyperledger/msp/orderer/files/msp/signcerts
            - name: orderer-msp-tlscacerts-mount
              mountPath: /etc/hyperledger/msp/orderer/files/msp/tlscacerts
            - name: orderer-tls-mount
              mountPath: /etc/hyperledger/msp/orderer/files/tls
            - name: configtx-mount
              mountPath: /etc/hyperledger/configtx/files/genesis.block
              subPath: genesis.block
            - name: configtx-mount
              mountPath: /etc/hyperledger/configtx/files/channel.tx
              subPath: channel.tx
            - name: configtx-mount
              mountPath: /etc/hyperledger/configtx/files/Org1MSPanchors.tx
              subPath: Org1MSPanchors.tx
            - name: configtx-mount
              mountPath: /etc/hyperledger/msp/peerOrg1/files/msp/config.yaml
              subPath: config.yaml
            - name: peer-admincerts-mount
              mountPath: /etc/hyperledger/msp/peerOrg1/files/msp/admincerts
            - name: peer-cacerts-mount
              mountPath: /etc/hyperledger/msp/peerOrg1/files/msp/cacerts
            - name: peer-keystore-mount
              mountPath: /etc/hyperledger/msp/peerOrg1/files/msp/keystore
            - name: peer-signcerts-mount
              mountPath: /etc/hyperledger/msp/peerOrg1/files/msp/signcerts
            - name: peer-tlscacerts-mount
              mountPath: /etc/hyperledger/msp/peerOrg1/files/msp/tlscacerts
            - name: peer-tls-mount
              mountPath: /etc/hyperledger/msp/peerOrg1/files/tls
      volumes:
        - name: orderer-storage
          emptyDir: {}
        - name: peer-storage
          emptyDir: {}
        - name: configtx
          emptyDir: {}
        - name: orderer-msp-admincerts-mount
          secret:
            secretName: o-cert-orderer-msp-admincerts
        - name: orderer-msp-cacerts-mount
          secret:
            secretName: o-cert-orderer-msp-cacerts
        - name: orderer-msp-keystore-mount
          secret:
            secretName: o-cert-orderer-msp-keystore
        - name: orderer-msp-signcerts-mount
          secret:
            secretName: o-cert-orderer-msp-signcerts
        - name: orderer-msp-tlscacerts-mount
          secret:
            secretName: o-cert-orderer-msp-tlscacerts
        - name: orderer-tls-mount
          secret:
            secretName: o-cert-orderer-tls
        - name: peer-admincerts-mount
          secret:
            secretName: p-cert-peer-msp-admincerts
        - name: peer-cacerts-mount
          secret:
            secretName: p-cert-peer-msp-cacerts
        - name: peer-keystore-mount
          secret:
            secretName: p-cert-peer-msp-keystore
        - name: peer-signcerts-mount
          secret:
            secretName: p-cert-peer-msp-signcerts
        - name: peer-tlscacerts-mount
          secret:
            secretName: p-cert-peer-msp-tlscacerts
        - name: peer-tls-mount
          secret:
            secretName: p-cert-peer-tls
        - name: configtx-mount
          configMap:
              name: channel-artifacts
              items:
              - key: genesis.block
                path: genesis.block
              - key: channel.tx
                path: channel.tx
              - key: Org1MSPanchors.tx
                path: Org1MSPanchors.tx
              - key: config.yaml
                path: config.yaml
      containers:
        - name: orderer-imfreemobile-com
          # image: busybox
          # command: ["sleep", "3600"]
          image: hyperledger/fabric-orderer:1.4.1
          command: ["orderer"]
          ports:
            - containerPort: 7050
          volumeMounts:
            - name: orderer-storage
              mountPath: /etc/hyperledger/msp/orderer
              readOnly: false
            - name: peer-storage
              mountPath: /etc/hyperledger/msp/peerOrg1
              readOnly: false
            - name: configtx
              mountPath: /etc/hyperledger/configtx
              readOnly: false
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: FABRIC_LOGGING_SPEC
              value: info
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_GENESISFILE
              value: /etc/hyperledger/configtx/genesis.block
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /etc/hyperledger/msp/orderer/msp