apiVersion: v1
kind: Service
metadata:
  name: peer0-org1-imfreemobile-com
spec:
  type: ClusterIP
  ports:
    - port: 7051
      targetPort: 7051
  selector:
    component: peer0-org1-imfreemobile-com