apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orderer-imfreemobile-com
  template:
    metadata:
      labels:
        component: orderer-imfreemobile-com
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: orderer-imfreemobile-com
          image: hyperledger/fabric-orderer:1.4.1
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
          command: ["orderer"]
          ports:
            - containerPort: 7050
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
              readOnly: false
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 200m
              memory: 1Gi
          env:
            - name: TZ
              value: "UTC"
            - name: GODEBUG
              value: "netdns=go"
            - name: FABRIC_LOGGING_SPEC
              value: info
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "false"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_GENESISFILE
              # value: /etc/hyperledger/configtx/genesis.block
              value: /shared/channel-artifacts/genesis.block
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            - name: ORDERER_GENERAL_LOCALMSPDIR
              # value: /etc/hyperledger/msp/orderer/msp
              value: /shared/crypto-config/ordererOrganizations/imfreemobile-com/orderers/orderer-imfreemobile-com/msp