apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orderer-imfreemobile-com
  template:
    metadata:
      labels:
        component: orderer-imfreemobile-com
    spec:
      initContainers:
        - name: configmap-copy
          image: busybox
          command: ['/bin/sh', '-c']
          args: ['cp -R /etc/hyperledger/shared/crypto-config/ordererOrganizations/imfreemobile.com/orderers/orderer.imfreemobile.com/* /etc/hyperledger/msp/orderer/ && cp -R /etc/hyperledger/shared/channel-artifacts/* /etc/hyperledger/configtx/ && cp -R /etc/hyperledger/shared/crypto-config/peerOrganizations/org1.imfreemobile.com/peers/peer0.org1.imfreemobile.com/* /etc/hyperledger/msp/peerOrg1/']
          volumeMounts:
            - name: orderer-storage
              mountPath: /etc/hyperledger/msp/orderer
            - name: peer-storage
              mountPath: /etc/hyperledger/msp/peerOrg1
            - name: configtx
              mountPath: /etc/hyperledger/configtx
            - name: shared-volume
              mountPath: /etc/hyperledger/shared
      volumes:
        - name: orderer-storage
          emptyDir: {}
        - name: peer-storage
          emptyDir: {}
        - name: configtx
          emptyDir: {}
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: orderer-imfreemobile-com
          image: hyperledger/fabric-orderer:1.4.1
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
          command: ["orderer"]
          ports:
            - containerPort: 7050
          volumeMounts:
            - name: orderer-storage
              mountPath: /etc/hyperledger/msp/orderer
              readOnly: false
            - name: peer-storage
              mountPath: /etc/hyperledger/msp/peerOrg1
              readOnly: false
            - name: configtx
              mountPath: /etc/hyperledger/configtx
              readOnly: false
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: TZ
              value: "UTC"
            - name: GODEBUG
              value: "netdns=go"
            - name: FABRIC_LOGGING_SPEC
              value: info
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "false"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_GENESISFILE
              value: /etc/hyperledger/configtx/genesis.block
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /etc/hyperledger/msp/orderer/msp